version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
   # restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - postgres-compose-network

volumes:
  db:
    driver: local

networks:
  postgres-compose-network:
    driver: bridge